-- ============================================================
-- Scraped Properties from SquareYards – Hennur Road & Thanisandra
-- All properties above ₹35,000/month
-- Run AFTER previous migrations
-- ============================================================

INSERT INTO js_properties (title, location, area, price, bhk, sqft, type, furnished, images, amenities, verified, available, description, deposit, floor, facing, nearby_places, sharing_type, posted_date, verification_fee, concierge_name) VALUES

-- Hennur Road Properties
('Rohan Upavan 2BHK', 'Hennur Main Road, Hennur', 'Hennur', 45000, 2, 1100, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-2.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift'], true, true, 'Well-maintained 2BHK in Rohan Upavan on Hennur Main Road. Semi-furnished with wardrobes and modular kitchen. The apartment offers a serene garden view from the 13th floor with excellent cross-ventilation and natural light.', 90000, '13th of 18', 'North', '[{"name":"Manyata Tech Park","distance":"3 km","type":"mall"},{"name":"Columbia Asia Hospital","distance":"2 km","type":"hospital"},{"name":"Hennur Bande Lake","distance":"1.2 km","type":"park"}]'::jsonb, 'Family', '2026-09-25'),

('Puravankara Palm Beach 2BHK', 'Hennur Main Road, Hennur', 'Hennur', 49000, 2, 1250, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-3.png'], ARRAY['Pool','Gym','Parking','Security','Power Backup','Lift','Clubhouse'], true, true, 'Elegant 2BHK in Puravankara Palm Beach on Hennur Road. Semi-furnished with wardrobes and kitchen cabinets. Offers a serene garden view from the 4th floor of a 20-story building with resort-style amenities.', 98000, '4th of 20', 'East', '[{"name":"Hennur Lake","distance":"800 m","type":"park"},{"name":"Manyata Tech Park","distance":"2.5 km","type":"mall"},{"name":"Aster CMI Hospital","distance":"3 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-24'),

('Purva Palm Beach 2BHK Furnished', 'Hennur Road, Hennur', 'Hennur', 50000, 2, 1232, 'Apartment', 'Furnished', ARRAY['/images/scene-4.png'], ARRAY['WiFi','AC','Gym','Pool','Parking','Security','Power Backup','Lift'], true, true, 'Fully furnished 2BHK in Purva Palm Beach on Hennur Road. Features split ACs, washing machine, refrigerator, and a modular kitchen. Park-facing unit on the 10th floor of a 19-story tower with premium interiors.', 100000, '10th of 19', 'West', '[{"name":"Hennur Bande Lake","distance":"600 m","type":"park"},{"name":"Elements Mall","distance":"4 km","type":"mall"},{"name":"Columbia Asia Hospital","distance":"2 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-23'),

('Casagrand Boulevard 2BHK', 'Hennur Road, Hennur', 'Hennur', 40000, 2, 1150, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-5.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Badminton Court'], true, true, 'Spacious 2BHK in Casagrand Boulevard on Hennur Road. Semi-furnished with wardrobes and modular kitchen. The gated community features a gymnasium, swimming pool, badminton court, and dedicated kids play areas.', 80000, '9th of 14', 'North', '[{"name":"Hennur Main Road","distance":"200 m","type":"restaurant"},{"name":"Manyata Tech Park","distance":"3.5 km","type":"mall"},{"name":"Bangalore Baptist Hospital","distance":"4 km","type":"hospital"}]'::jsonb, 'Any', '2026-09-22'),

('Shriram Luxor 2BHK', 'Hennur Road, Hennur', 'Hennur', 38000, 2, 1200, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-1.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','CCTV'], true, true, 'Well-designed 2BHK in Shriram Luxor on Hennur Road. Semi-furnished with wardrobes and modular kitchen. Features a community view from the 8th floor of a 14-story building with 24x7 security and power backup.', 76000, '8th of 14', 'East', '[{"name":"Hennur Road Market","distance":"500 m","type":"mall"},{"name":"Narayana Health","distance":"4 km","type":"hospital"},{"name":"Kannur Lake","distance":"2 km","type":"park"}]'::jsonb, 'Any', '2026-09-21'),

('Kolte Patil Raaga 2BHK', 'Hennur Road, Hennur', 'Hennur', 36000, 2, 1052, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-2.png'], ARRAY['Pool','Gym','Parking','Security','Power Backup','Lift'], true, true, 'Well-maintained 2BHK in Kolte Patil Raaga, a premium gated community on Hennur Road. Semi-furnished with attractive false ceiling, lift access, and excellent ventilation. Amenities include swimming pool and gym.', 72000, '5th of 12', 'South', '[{"name":"Hennur Bande Lake","distance":"1 km","type":"park"},{"name":"Columbia Asia Hospital","distance":"2.5 km","type":"hospital"},{"name":"Manyata Tech Park","distance":"3 km","type":"mall"}]'::jsonb, 'Family', '2026-09-20'),

('Mantri Webcity 3BHK Premium', 'Hennur-Bagalur Road, Hennur', 'Hennur', 50000, 3, 1780, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-3.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse','Jogging Track'], true, true, 'Premium 3BHK in Mantri Webcity along Hennur-Bagalur Road. Semi-furnished with wardrobes in all bedrooms and modular kitchen. Offers a desirable garden view from the 17th floor with 1 dedicated parking space.', 100000, '17th of 22', 'North', '[{"name":"Kannur Lake","distance":"2 km","type":"park"},{"name":"Lulu Mall (upcoming)","distance":"5 km","type":"mall"},{"name":"Narayana Health","distance":"4 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-26'),

('Sethna Power Tower 3BHK', 'Hennur Main Road, Hennur', 'Hennur', 60000, 3, 1820, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-4.png'], ARRAY['Pool','Gym','Parking','Security','Power Backup','CCTV','Lift','Clubhouse'], true, true, 'Spacious 3BHK in Sethna Power Tower on Hennur Road. Semi-furnished with modular kitchen and wardrobes. Pool-facing unit on the 4th floor of an 11-story building in a gated community with 24x7 security and CCTV surveillance.', 120000, '4th of 11', 'West', '[{"name":"Hennur Bande Lake","distance":"1 km","type":"park"},{"name":"Manyata Tech Park","distance":"2.5 km","type":"mall"},{"name":"Aster CMI Hospital","distance":"3 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-27'),

('Arge Helios 3BHK', 'Hennur Road, Hennur', 'Hennur', 70000, 3, 2357, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-5.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse','Tennis Court'], true, true, 'Luxurious 3BHK in Arge Helios on Hennur Road. This expansive 2357 sqft apartment features 3 bedrooms with attached bathrooms, a garden view from the 13th floor of a 14-story building, and 1 dedicated parking space. Premium semi-furnished unit.', 140000, '13th of 14', 'East', '[{"name":"Hennur Main Road","distance":"300 m","type":"restaurant"},{"name":"Columbia Asia Hospital","distance":"2 km","type":"hospital"},{"name":"Manyata Tech Park","distance":"3 km","type":"mall"}]'::jsonb, 'Family', '2026-09-28'),

('Adonai Glory 3BHK', 'Kothanur, near Hennur', 'Hennur', 60000, 3, 1450, 'Apartment', 'Furnished', ARRAY['/images/scene-1.png'], ARRAY['WiFi','AC','Gym','Parking','Security','Power Backup','Lift','CCTV'], true, true, 'Fully furnished 3BHK in Adonai Glory at Kothanur near Hennur. Features split ACs, beds, wardrobes, washing machine, and a fully equipped kitchen. Located on the 2nd floor of an 8-story building in a gated society.', 120000, '2nd of 8', 'North', '[{"name":"Kothanur Lake","distance":"800 m","type":"park"},{"name":"Hennur Main Road","distance":"2 km","type":"restaurant"},{"name":"Narayana Health","distance":"5 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-22'),

-- Thanisandra Properties
('Nikoo Homes IV 2BHK', 'Bhartiya City, Thanisandra', 'Thanisandra', 47000, 2, 1100, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-2.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse'], true, true, 'Brand new east-facing 2BHK in Nikoo Homes IV at Bhartiya City, Thanisandra. Semi-furnished pool-facing unit on the 20th floor with 2 bathrooms. Rent includes maintenance. Part of the massive Bhartiya City integrated township.', 150000, '20th of 25', 'East', '[{"name":"Bhartiya Mall of Bangalore","distance":"500 m","type":"mall"},{"name":"Leena Multispeciality Hospital","distance":"1.5 km","type":"hospital"},{"name":"Thanisandra Lake","distance":"2 km","type":"park"}]'::jsonb, 'Family', '2026-09-26'),

('KSR Cordelia 2BHK', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 40000, 2, 1100, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-3.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift'], true, true, 'Well-designed 2BHK in KSR Cordelia on Thanisandra Main Road. Semi-furnished with wardrobes and modular kitchen. The gated community offers excellent amenities and is well-connected to Manyata Tech Park.', 80000, '6th of 14', 'North', '[{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"Thanisandra Main Road","distance":"200 m","type":"restaurant"},{"name":"Aster CMI Hospital","distance":"4 km","type":"hospital"}]'::jsonb, 'Any', '2026-09-25'),

('Mantri Lithos 2BHK', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 50000, 2, 1008, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-4.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Badminton Court','Clubhouse'], true, true, 'Premium 2BHK in Mantri Lithos on Thanisandra Main Road. Semi-furnished with high-rise views from the 20th floor. Features gymnasium, swimming pool, and badminton court. Excellent connectivity to IT corridors.', 100000, '20th of 24', 'West', '[{"name":"Manyata Tech Park","distance":"1.5 km","type":"mall"},{"name":"Thanisandra Lake","distance":"1 km","type":"park"},{"name":"Columbia Asia Hospital","distance":"3 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-24'),

('Trendsquares Ambience 2BHK', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 35000, 2, 1195, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-5.png'], ARRAY['Parking','Security','Power Backup','Lift','CCTV'], true, true, 'Spacious 2BHK in Trendsquares Ambience on Thanisandra Main Road. Semi-furnished unit on the 13th floor of a 14-story building with garden views. Features 24x7 security and CCTV surveillance.', 70000, '13th of 14', 'South', '[{"name":"Thanisandra Main Road","distance":"100 m","type":"restaurant"},{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"GKVK Campus","distance":"3 km","type":"school"}]'::jsonb, 'Any', '2026-09-23'),

('Arvind Sporcia 2BHK', 'Thanisandra, near Jakkur', 'Thanisandra', 44000, 2, 1260, 'Apartment', 'Furnished', ARRAY['/images/scene-1.png'], ARRAY['WiFi','AC','Gym','Pool','Parking','Security','Power Backup','Lift'], true, true, 'Fully furnished 2BHK in Arvind Sporcia near Thanisandra. Brand new apartment built within the last year, located on the 2nd floor with 2 bathrooms and 1 dedicated parking spot. Close to Manyata Tech Hub.', 88000, '2nd of 16', 'East', '[{"name":"Manyata Tech Park","distance":"2.5 km","type":"mall"},{"name":"Jakkur Aerodrome","distance":"2 km","type":"park"},{"name":"Aster CMI Hospital","distance":"3.5 km","type":"hospital"}]'::jsonb, 'Any', '2026-09-22'),

('DS Max Skycity 3BHK Tower A', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 50000, 3, 2080, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-2.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse','Badminton Court'], true, true, 'Spacious 3BHK in DS Max Skycity on Thanisandra Main Road. This impressive 2080 sqft unit offers a garden view from the 17th floor of a 24-story building. Semi-furnished with wardrobes, modular kitchen, and 1 dedicated parking spot.', 100000, '17th of 24', 'North', '[{"name":"Thanisandra Lake","distance":"1.5 km","type":"park"},{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"Columbia Asia Hospital","distance":"3 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-27'),

('DS Max Skycity 3BHK Tower B', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 50000, 3, 1800, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-3.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Badminton Court'], true, true, 'Premium 3BHK in DS Max Skycity Tower B on Thanisandra Main Road. 1800 sqft semi-furnished unit on the 10th floor of a 25-story building with garden view. Features gymnasium, swimming pool, and badminton court amenities.', 100000, '10th of 25', 'East', '[{"name":"Thanisandra Main Road","distance":"200 m","type":"restaurant"},{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"Aster CMI Hospital","distance":"3.5 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-26'),

('Trendsquares Ambience 3BHK', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 55000, 3, 1590, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-4.png'], ARRAY['Gym','Parking','Security','Power Backup','Lift','CCTV','Clubhouse'], true, true, 'Well-designed 3BHK in Trendsquares Ambience on Thanisandra Main Road. Semi-furnished with wardrobes and modular kitchen. Located on the 2nd floor of a 19-story development with garden views and excellent amenities.', 110000, '2nd of 19', 'West', '[{"name":"Thanisandra Lake","distance":"1 km","type":"park"},{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"GKVK Campus","distance":"3 km","type":"school"}]'::jsonb, 'Family', '2026-09-25'),

('Purva Atmosphere 3BHK Premium', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 70000, 3, 1680, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-5.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse','Jogging Track'], true, true, 'Premium 3BHK in Puravankara Purva Atmosphere on Thanisandra Main Road. This 1680 sqft semi-furnished unit is on the 16th floor with 3 bedrooms and 3 bathrooms. The complex offers world-class amenities including a clubhouse and jogging track.', 140000, '16th of 20', 'North', '[{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"GKVK Campus","distance":"3 km","type":"school"},{"name":"Thanisandra Lake","distance":"1 km","type":"park"}]'::jsonb, 'Family', '2026-09-28'),

('Purva Atmosphere 3BHK Executive', 'Thanisandra Main Road, Thanisandra', 'Thanisandra', 80000, 3, 1686, 'Apartment', 'Semi-Furnished', ARRAY['/images/scene-1.png'], ARRAY['Gym','Pool','Parking','Security','Power Backup','Lift','Clubhouse','Jogging Track','Tennis Court'], true, true, 'Executive 3BHK in Puravankara Purva Atmosphere on Thanisandra Main Road. This premium 1686 sqft unit on the 10th floor features north-east facing orientation, 3 bedrooms with 3 bathrooms, 1 car parking, and ₹10,000 maintenance included. Top-tier amenities.', 160000, '10th of 19', 'North-East', '[{"name":"Manyata Tech Park","distance":"2 km","type":"mall"},{"name":"Thanisandra Lake","distance":"1 km","type":"park"},{"name":"Columbia Asia Hospital","distance":"3 km","type":"hospital"}]'::jsonb, 'Family', '2026-09-29');
